sudo: required

service:
  - docker
#this is a comment

before_install:
  - docker build -t ar-zekavat\docker-react -f Dockerfile.dev .


script: 
  - docker run ar-zekavat\docker-react run npm test
  
