sudo: required

service:
  - docker
#this is a comment

before_install:
  - docker build -t alirezazekvat\docker-react -f Dockerfile.dev .


script:
  - docker run alirezazekvat\docker-react npm run coverage
