sudo: required

 service:
  - docker


  before_install:
   - docker build -t alirezazekavat\docker-react -f Dockerfile.dev .


  script: 
   - docker run alirezazekavat\docker-react run npm test -- -- coverage 
   
