sudo: required

service:
  - docker
#this is a comment

before_install:
  - docker build -t alirezazekavat\docker-react -f Dockerfile.dev .


script: 
  - docker run alirezazekavat\docker-react run npm test
  
